"
I'm a five part component.

```
-----------------
|  |_________|  |
|  |         |  |
|  |         |  |
|  |_________|  |
|  |         |  |
-----------------
```

I have 
- a leftColumn whose width can change
- a rightColumn whose width can change
- a top row whose height can change
- a bottom row whose height can change
- a center zone


"
Class {
	#name : 'ManifestPanel',
	#superclass : 'PackageManifest',
	#category : 'Panel-Manifest',
	#package : 'Panel',
	#tag : 'Manifest'
}
